declare var require;
var path = require('path');
var ts = require('typescript');
var fs = require('fs');
var mkdirp = require('mkdirp');
export const copy  = (gulp, config) => {

	gulp.task('copy:dev', () => {
		return gulp.src(config.staticFiles)
		  .pipe(gulp.dest(config.dist));
	});

  gulp.task('copy:angular', () => {
    [
      'node_modules/angular2/ts/platform/browser.ts',
      'node_modules/angular2/ts/core.ts',
      'node_modules/angular2/ts/router.ts',
      // /app/services/Auth.js
      // /app/services/Backend.js
      // /app/app/app.js
      'node_modules/angular2/ts/src/core/angular_entrypoint.ts',
      'node_modules/angular2/ts/src/platform/browser_common.ts',
      'node_modules/angular2/ts/src/facade/lang.ts',
      'node_modules/angular2/ts/compiler.ts',
      'node_modules/angular2/ts/src/core/reflection/reflection_capabilities.ts',
      'node_modules/angular2/ts/src/platform/browser/xhr_impl.ts',
      'node_modules/angular2/ts/src/core/di.ts',
      'node_modules/angular2/ts/src/core/metadata.ts',
      'node_modules/angular2/ts/src/core/util.ts',
      'node_modules/angular2/ts/src/core/prod_mode.ts',
      'node_modules/angular2/ts/src/facade/facade.ts',
      'node_modules/angular2/ts/src/core/application_ref.ts',
      'node_modules/angular2/ts/src/core/application_tokens.ts',
      'node_modules/angular2/ts/src/core/zone.ts',
      'node_modules/angular2/ts/src/core/render.ts',
      'node_modules/angular2/ts/src/core/linker.ts',
      'node_modules/angular2/ts/src/core/debug/debug_element.ts',
      'node_modules/angular2/ts/src/core/testability/testability.ts',
      'node_modules/angular2/ts/src/core/change_detection.ts',
      'node_modules/angular2/ts/src/core/platform_directives_and_pipes.ts',
      'node_modules/angular2/ts/src/core/platform_common_providers.ts',
      'node_modules/angular2/ts/src/core/application_common_providers.ts',
      'node_modules/angular2/ts/src/core/reflection/reflection.ts',
      'node_modules/angular2/ts/src/core/reflection/types.ts',
      'node_modules/angular2/ts/src/core/reflection/platform_reflection_capabilities.ts',
      'node_modules/angular2/ts/src/router/router.ts',
      'node_modules/angular2/ts/src/router/router_outlet.ts',
      'node_modules/angular2/ts/src/router/router_link.ts',
      'node_modules/angular2/ts/src/router/interfaces.ts',
      'node_modules/angular2/ts/src/router/instruction.ts',
      'node_modules/angular2/ts/src/router/platform_location.ts',
      'node_modules/angular2/ts/src/router/route_registry.ts',
      'node_modules/angular2/ts/src/router/location_strategy.ts',
      'node_modules/angular2/ts/src/router/hash_location_strategy.ts',
      'node_modules/angular2/ts/src/router/path_location_strategy.ts',
      'node_modules/angular2/ts/src/router/location.ts',
      'node_modules/angular2/ts/src/router/route_config_decorator.ts',
      'node_modules/angular2/ts/src/router/route_definition.ts',
      'node_modules/angular2/ts/src/router/lifecycle_annotations.ts',
      'node_modules/angular2/ts/src/facade/exceptions.ts',
      // /firebase/lib/firebase-web.js
      // 'node_modules/rxjs/Observable.ts',
      // 'node_modules/rxjs/subject/ReplaySubject.ts',
      // /app/services/Nav.js
      // /app/components/header.js
      // /app/components/sidenav.js
      // /app/components/toast.js
      // /app/components/Home.js
      // /app/components/About.js
      'node_modules/angular2/ts/common.ts',
      'node_modules/angular2/ts/src/platform/dom/dom_adapter.ts',
      'node_modules/angular2/ts/src/platform/dom/events/dom_events.ts',
      'node_modules/angular2/ts/src/platform/dom/events/key_events.ts',
      'node_modules/angular2/ts/src/platform/dom/events/hammer_gestures.ts',
      'node_modules/angular2/ts/src/platform/dom/dom_tokens.ts',
      'node_modules/angular2/ts/src/platform/dom/dom_renderer.ts',
      'node_modules/angular2/ts/src/platform/dom/shared_styles_host.ts',
      'node_modules/angular2/ts/src/animate/browser_details.ts',
      'node_modules/angular2/ts/src/animate/animation_builder.ts',
      'node_modules/angular2/ts/src/platform/browser/browser_adapter.ts',
      'node_modules/angular2/ts/src/platform/browser/testability.ts',
      'node_modules/angular2/ts/src/core/profile/wtf_init.ts',
      'node_modules/angular2/ts/src/platform/dom/events/event_manager.ts',
      'node_modules/angular2/ts/src/platform/browser/title.ts',
      'node_modules/angular2/ts/platform/common_dom.ts',
      'node_modules/angular2/ts/src/platform/browser/tools/tools.ts',
      'node_modules/angular2/ts/src/compiler/url_resolver.ts',
      'node_modules/angular2/ts/src/compiler/xhr.ts',
      'node_modules/angular2/ts/src/compiler/compiler.ts',
      'node_modules/angular2/ts/src/facade/promise.ts',
      'node_modules/angular2/ts/src/core/di/metadata.ts',
      'node_modules/angular2/ts/src/core/di/decorators.ts',
      'node_modules/angular2/ts/src/core/di/forward_ref.ts',
      'node_modules/angular2/ts/src/core/di/injector.ts',
      'node_modules/angular2/ts/src/core/di/provider.ts',
      'node_modules/angular2/ts/src/core/di/key.ts',
      'node_modules/angular2/ts/src/core/di/exceptions.ts',
      'node_modules/angular2/ts/src/core/di/opaque_token.ts',
      'node_modules/angular2/ts/src/core/util/decorators.ts',
      'node_modules/angular2/ts/src/core/metadata/di.ts',
      'node_modules/angular2/ts/src/core/metadata/directives.ts',
      'node_modules/angular2/ts/src/core/metadata/view.ts',
      'node_modules/angular2/ts/src/facade/async.ts',
      'node_modules/angular2/ts/src/facade/exception_handler.ts',
      'node_modules/angular2/ts/src/core/zone/ng_zone.ts',
      'node_modules/angular2/ts/src/facade/collection.ts',
      'node_modules/angular2/ts/src/core/linker/dynamic_component_loader.ts',
      'node_modules/angular2/ts/src/core/linker/view_ref.ts',
      'node_modules/angular2/ts/src/core/console.ts',
      'node_modules/angular2/ts/src/core/profile/profile.ts',
      'node_modules/angular2/ts/src/core/render/api.ts',
      'node_modules/angular2/ts/src/core/linker/directive_resolver.ts',
      'node_modules/angular2/ts/src/core/linker/view_resolver.ts',
      'node_modules/angular2/ts/src/core/linker/compiler.ts',
      'node_modules/angular2/ts/src/core/linker/view_manager.ts',
      'node_modules/angular2/ts/src/core/linker/query_list.ts',
      'node_modules/angular2/ts/src/core/linker/element_ref.ts',
      'node_modules/angular2/ts/src/core/linker/template_ref.ts',
      'node_modules/angular2/ts/src/core/linker/view_container_ref.ts',
      'node_modules/angular2/ts/src/core/change_detection/change_detection.ts',
      'node_modules/angular2/ts/src/core/linker/view.ts',
      'node_modules/angular2/ts/src/core/linker/view_pool.ts',
      'node_modules/angular2/ts/src/core/linker/view_manager_utils.ts',
      'node_modules/angular2/ts/src/core/linker/view_listener.ts',
      'node_modules/angular2/ts/src/core/linker/proto_view_factory.ts',
      'node_modules/angular2/ts/src/core/linker/pipe_resolver.ts',
      'node_modules/angular2/ts/src/core/reflection/reflector.ts',
      'node_modules/angular2/ts/src/router/route_lifecycle_reflector.ts',
      'node_modules/angular2/ts/src/router/route_config_impl.ts',
      'node_modules/angular2/ts/src/router/route_recognizer.ts',
      'node_modules/angular2/ts/src/router/component_recognizer.ts',
      'node_modules/angular2/ts/src/router/route_config_nomalizer.ts',
      'node_modules/angular2/ts/src/router/url_parser.ts',
      'node_modules/angular2/ts/src/router/lifecycle_annotations_impl.ts',
      // 'node_modules/rxjs/Subscriber.ts',
      // 'node_modules/rxjs/util/root.ts',
      // 'node_modules/rxjs/util/SymbolShim.ts',
      // 'node_modules/rxjs/symbol/rxSubscriber.ts',
      // 'node_modules/rxjs/Subject.ts',
      // 'node_modules/rxjs/scheduler/queue.ts',
      'node_modules/angular2/ts/src/common/pipes.ts',
      'node_modules/angular2/ts/src/common/directives.ts',
      'node_modules/angular2/ts/src/common/forms/directives/form_interface.ts',
      'node_modules/angular2/ts/src/common/forms.ts',
      'node_modules/angular2/ts/src/common/common_directives.ts',
      'node_modules/angular2/ts/src/platform/dom/events/hammer_common.ts',
      'node_modules/angular2/ts/src/facade/math.ts',
      'node_modules/angular2/ts/src/animate/css_animation_builder.ts',
      'node_modules/angular2/ts/src/platform/dom/debug/by.ts',
      'node_modules/angular2/ts/src/platform/dom/debug/debug_element_view_listener.ts',
      'node_modules/angular2/ts/src/platform/browser/tools/common_tools.ts',
      'node_modules/angular2/ts/src/core/render/view_factory.ts',
      'node_modules/angular2/ts/src/core/render/view.ts',
      'node_modules/angular2/ts/src/platform/dom/util.ts',
      'node_modules/angular2/ts/src/compiler/runtime_compiler.ts',
      'node_modules/angular2/ts/src/compiler/template_compiler.ts',
      'node_modules/angular2/ts/src/compiler/directive_metadata.ts',
      'node_modules/angular2/ts/src/compiler/source_module.ts',
      'node_modules/angular2/ts/src/compiler/template_ast.ts',
      'node_modules/angular2/ts/src/compiler/template_parser.ts',
      'node_modules/angular2/ts/src/compiler/html_parser.ts',
      'node_modules/angular2/ts/src/compiler/template_normalizer.ts',
      'node_modules/angular2/ts/src/compiler/runtime_metadata.ts',
      'node_modules/angular2/ts/src/compiler/change_detector_compiler.ts',
      'node_modules/angular2/ts/src/compiler/style_compiler.ts',
      'node_modules/angular2/ts/src/compiler/command_compiler.ts',
      'node_modules/angular2/ts/src/compiler/schema/element_schema_registry.ts',
      'node_modules/angular2/ts/src/compiler/schema/dom_element_schema_registry.ts',
      'node_modules/angular2/ts/src/platform/browser/generic_browser_adapter.ts',
      'node_modules/angular2/ts/src/core/di/type_literal.ts',
      // 'node_modules/rxjs/observable/fromPromise.ts',
      // 'node_modules/rxjs/operator/toPromise.ts',
      'node_modules/angular2/ts/src/core/profile/wtf_impl.ts',
      'node_modules/angular2/ts/src/core/linker/template_commands.ts',
      'node_modules/angular2/ts/src/core/change_detection/differs/iterable_differs.ts',
      'node_modules/angular2/ts/src/core/change_detection/differs/default_iterable_differ.ts',
      'node_modules/angular2/ts/src/core/change_detection/differs/keyvalue_differs.ts',
      'node_modules/angular2/ts/src/core/change_detection/differs/default_keyvalue_differ.ts',
      'node_modules/angular2/ts/src/core/change_detection/parser/ast.ts',
      'node_modules/angular2/ts/src/core/change_detection/parser/lexer.ts',
      'node_modules/angular2/ts/src/core/change_detection/parser/parser.ts',
      'node_modules/angular2/ts/src/core/change_detection/parser/locals.ts',
      'node_modules/angular2/ts/src/core/change_detection/exceptions.ts',
      'node_modules/angular2/ts/src/core/change_detection/interfaces.ts',
      'node_modules/angular2/ts/src/core/change_detection/constants.ts',
      'node_modules/angular2/ts/src/core/change_detection/proto_change_detector.ts',
      'node_modules/angular2/ts/src/core/change_detection/jit_proto_change_detector.ts',
      'node_modules/angular2/ts/src/core/change_detection/binding_record.ts',
      'node_modules/angular2/ts/src/core/change_detection/directive_record.ts',
      'node_modules/angular2/ts/src/core/change_detection/dynamic_change_detector.ts',
      'node_modules/angular2/ts/src/core/change_detection/change_detector_ref.ts',
      'node_modules/angular2/ts/src/core/change_detection/change_detection_util.ts',
      'node_modules/angular2/ts/src/core/change_detection/pipe_transform.ts',
      'node_modules/angular2/ts/src/core/render/util.ts',
      'node_modules/angular2/ts/src/core/linker/element_injector.ts',
      'node_modules/angular2/ts/src/core/pipes/pipes.ts',
      'node_modules/angular2/ts/src/core/pipes/pipe_provider.ts',
      'node_modules/angular2/ts/src/core/linker/element_binder.ts',
      'node_modules/angular2/ts/src/router/path_recognizer.ts',
      'node_modules/angular2/ts/src/router/async_route_handler.ts',
      'node_modules/angular2/ts/src/router/sync_route_handler.ts',
      // 'node_modules/rxjs/util/noop.ts',
      // 'node_modules/rxjs/util/throwError.ts',
      // 'node_modules/rxjs/util/tryOrOnError.ts',
      // 'node_modules/rxjs/Subscription.ts',
      // 'node_modules/rxjs/subject/SubjectSubscription.ts',
      // 'node_modules/rxjs/scheduler/QueueScheduler.ts',
      'node_modules/angular2/ts/src/common/pipes/async_pipe.ts',
      'node_modules/angular2/ts/src/common/pipes/uppercase_pipe.ts',
      'node_modules/angular2/ts/src/common/pipes/lowercase_pipe.ts',
      'node_modules/angular2/ts/src/common/pipes/json_pipe.ts',
      'node_modules/angular2/ts/src/common/pipes/slice_pipe.ts',
      'node_modules/angular2/ts/src/common/pipes/date_pipe.ts',
      'node_modules/angular2/ts/src/common/pipes/number_pipe.ts',
      'node_modules/angular2/ts/src/common/directives/ng_class.ts',
      'node_modules/angular2/ts/src/common/directives/ng_for.ts',
      'node_modules/angular2/ts/src/common/directives/ng_if.ts',
      'node_modules/angular2/ts/src/common/directives/ng_style.ts',
      'node_modules/angular2/ts/src/common/directives/ng_switch.ts',
      'node_modules/angular2/ts/src/common/directives/observable_list_diff.ts',
      'node_modules/angular2/ts/src/common/directives/core_directives.ts',
      'node_modules/angular2/ts/src/common/forms/model.ts',
      'node_modules/angular2/ts/src/common/forms/directives/abstract_control_directive.ts',
      'node_modules/angular2/ts/src/common/forms/directives/control_container.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_control_name.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_form_control.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_model.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_control.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_control_group.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_form_model.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_form.ts',
      'node_modules/angular2/ts/src/common/forms/directives/control_value_accessor.ts',
      'node_modules/angular2/ts/src/common/forms/directives/default_value_accessor.ts',
      'node_modules/angular2/ts/src/common/forms/directives/ng_control_status.ts',
      'node_modules/angular2/ts/src/common/forms/directives/checkbox_value_accessor.ts',
      'node_modules/angular2/ts/src/common/forms/directives/select_control_value_accessor.ts',
      'node_modules/angular2/ts/src/common/forms/directives.ts',
      'node_modules/angular2/ts/src/common/forms/validators.ts',
      'node_modules/angular2/ts/src/common/forms/directives/validators.ts',
      'node_modules/angular2/ts/src/common/forms/form_builder.ts',
      'node_modules/angular2/ts/src/animate/css_animation_options.ts',
      'node_modules/angular2/ts/src/animate/animation.ts',
      'node_modules/angular2/ts/src/facade/browser.ts',
      'node_modules/angular2/ts/src/compiler/util.ts',
      'node_modules/angular2/ts/src/compiler/selector.ts',
      'node_modules/angular2/ts/src/core/linker/interfaces.ts',
      'node_modules/angular2/ts/src/compiler/html_tags.ts',
      'node_modules/angular2/ts/src/compiler/parse_util.ts',
      'node_modules/angular2/ts/src/compiler/template_preparser.ts',
      'node_modules/angular2/ts/src/compiler/style_url_resolver.ts',
      'node_modules/angular2/ts/src/compiler/html_ast.ts',
      'node_modules/angular2/ts/src/compiler/html_lexer.ts',
      'node_modules/angular2/ts/src/core/change_detection/change_detection_jit_generator.ts',
      'node_modules/angular2/ts/src/compiler/change_definition_factory.ts',
      'node_modules/angular2/ts/src/transform/template_compiler/change_detector_codegen.ts',
      'node_modules/angular2/ts/src/core/linker/directive_lifecycle_reflector.ts',
      'node_modules/angular2/ts/src/compiler/shadow_css.ts',
      'node_modules/angular2/ts/src/core/change_detection/pipe_lifecycle_reflector.ts',
      'node_modules/angular2/ts/src/core/change_detection/event_binding.ts',
      'node_modules/angular2/ts/src/core/change_detection/coalesce.ts',
      'node_modules/angular2/ts/src/core/change_detection/proto_record.ts',
      'node_modules/angular2/ts/src/core/change_detection/abstract_change_detector.ts',
      'node_modules/angular2/ts/src/core/change_detection/pipes.ts',
      'node_modules/angular2/ts/src/core/linker/event_config.ts',
      // 'node_modules/rxjs/scheduler/QueueAction.ts',
      // 'node_modules/rxjs/scheduler/FutureAction.ts',
      'node_modules/angular2/ts/src/common/pipes/invalid_pipe_argument_exception.ts',
      'node_modules/angular2/ts/src/facade/intl.ts',
      'node_modules/angular2/ts/src/common/forms/directives/shared.ts',
      'node_modules/angular2/ts/src/common/forms/directives/number_value_accessor.ts',
      'node_modules/angular2/ts/src/core/change_detection/codegen_name_util.ts',
      'node_modules/angular2/ts/src/core/change_detection/codegen_logic_util.ts',
      'node_modules/angular2/ts/src/core/change_detection/codegen_facade.ts',
      'node_modules/angular2/ts/src/core/change_detection/observable_facade.ts',
      'node_modules/angular2/ts/src/common/forms/directives/normalize_validator.ts'
    ].map(mod => {
      var sourceContents = fs.readFileSync(path.resolve(mod)).toString();
      console.log('source contents gotten', mod);
      return {
        path: mod.replace('node_modules/','').replace('/ts/','/').replace(/\.ts$/, '.js'),
        contents: ts.transpile(sourceContents, {
            module: ts.ModuleKind.System,
            emitDecoratorMetadata: true,
            experimentalDecorators: true,
            emitOnError: true,
            target: ts.ScriptTarget.ES5
          },
          mod,
          null,
          null // mod.replace('node_modules/','').replace('/ts/','/').replace(/\.ts$/,'.js')
        )
      }
    }).forEach(mod => {
      console.log('mkdirp', path.resolve('./dist', mod.path.replace(/[a-zA-Z\_0-9]*\.js$/, '')))
      mkdirp.sync(path.resolve('./dist', mod.path.replace(/[a-zA-Z\_0-9]*\.js$/, '')))
      if (mod.path.indexOf('interfaces') > -1) console.log('contents', mod.contents);
      console.log('writing file', mod.path)
      fs.writeFileSync(path.resolve('./dist', mod.path), mod.contents || '// Empty File');
    })
  });
  gulp.task('copy:angular-polyfills', makeCopyFn('angular-polyfills'))
  gulp.task('copy:typescript', makeCopyFn('typescript'));
  gulp.task('copy:rxjs', makeCopyFn('rxjs'));
  gulp.task('copy:reflect-metadata', makeCopyFn('reflect-metadata'));
  gulp.task('copy:systemjs', makeCopyFn('systemjs'));
  gulp.task('copy:zone.js', makeCopyFn('zone.js'));
  gulp.task('copy:firebase', makeCopyFn('firebase'));

  gulp.task('copy:all', [
    'copy:dev',
    'copy:angular',
    'copy:angular-polyfills',
    'copy:typescript',
    'copy:rxjs',
    'copy:reflect-metadata',
    'copy:zone.js',
    'copy:firebase',
    'copy:systemjs'
  ]);


  function makeCopyFn(name:string): Function {
    return () => {
      return gulp.src(config[name])
        .pipe(gulp.dest(path.resolve(config['dist'], name)));
    }
  }

};
